# Generated by Django 2.2.2 on 2019-06-20 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=8)),
                ('longitude', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Dob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('age', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('postcode', models.IntegerField()),
                ('coordinates', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webapp.Coordinates')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('salt', models.CharField(max_length=255)),
                ('md5', models.CharField(max_length=255)),
                ('sha1', models.CharField(max_length=255)),
                ('sha256', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('first', models.CharField(max_length=255)),
                ('last', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('large', models.CharField(max_length=255)),
                ('medium', models.CharField(max_length=255)),
                ('thumbnail', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Registered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('age', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset', models.CharField(max_length=5)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('cell', models.CharField(max_length=255)),
                ('nat', models.CharField(max_length=3)),
                ('dob', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webapp.Dob')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webapp.Location')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Login')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webapp.Name')),
                ('picture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webapp.Picture')),
                ('registered', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webapp.Registered')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webapp.Id')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='timezone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.TimeZone'),
        ),
    ]
